name: mmeg_m2_rnaseq_bash_and_r
# new env for the MEG M2 RNAseq course, created in 2022
# using https://github.com/Scaburet/meg_m2_rnaseq_bash and https://github.com/Scaburet/meg_m2_rnaseq_r repositories

# channels priority
# see https://bioconda.github.io/
# conda-forge has highest priority
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  # Jupyter dependencies
  - jupyterhub>=1.5,<2
  - jupyterlab>=3.2,<4
  - jupyter-resource-usage
  - jupyterlab-topbar
  - jupyterlab-topbar-text
  - jupyterlab-system-monitor
  - nodejs
  - gfortran_linux-64
  - pip
  # Jupyter archive
  # https://github.com/jupyterlab-contrib/jupyter-archive
  - jupyter-archive
  - pip:
    - bash_kernel
  # For the M2 course:
  - fastqc
  - fastp
  - bowtie
  - samtools
  - multiqc
  - qualimap
  - bedtools
  - htseq
  # R environment
  - r-irkernel
  - r-base>=4
  - r-tidyverse
  - r-rcpp
  # for the M2 course 
  - r-devtools
  - r-Matrix
  - r-lattice
  - r-fdrtool
  - r-rpart
  - r-RSQLite
  - r-gplots
  - r-locfit
