name: mmeg_m2_rnaseq_r
# new env for the MEG M2 RNAseq course, created in 2022

# channels priority
# see https://bioconda.github.io/
# conda-forge has highest priority
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  # Jupyter dependencies
  - jupyterhub>=1.5,<2
  - jupyterlab>=3.2,<4
  - jupyter-resource-usage
  - jupyterlab-topbar
  - jupyterlab-topbar-text
  - jupyterlab-system-monitor
  - nodejs
  - libgomp
  - pip
  # Jupyter archive
  # https://github.com/jupyterlab-contrib/jupyter-archive
  - jupyter-archive
  # R environment
  - r-irkernel
  - r-base>=4
  - r-tidyverse
  # JupyterLab Variable inspector
  # https://github.com/lckr/jupyterlab-variableInspector
  # Disabled due to bug https://github.com/lckr/jupyterlab-variableInspector/issues/122
  # - r-repr
  # - pip:
    # - lckr-jupyterlab-variableinspector
  # for the M2 course  
  - r-Matrix
  - r-lattice
  - r-fdrtool
  - r-rpart
  - r-RSQLite
  - r-gplots
  - r-locfit
