name: mmeg_m2_rnaseq_bash_and_r
# new env for the MEG M2 RNAseq course, created in 2022
# using https://github.com/Scaburet/meg_m2_rnaseq_bash and https://github.com/Scaburet/meg_m2_rnaseq_r repositories

# channels priority
# see https://bioconda.github.io/
# conda-forge has highest priority
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  # Jupyter dependencies
  - jupyterhub>=1.5,<2
  - jupyterlab>=3.2,<4
  - jupyter-resource-usage
  - jupyterlab-topbar
  - jupyterlab-topbar-text
  - jupyterlab-system-monitor
  - nodejs
  # fortran required for some r packages
  - gfortran_linux-64
  # Python environment
  - python>=3.8
  - pip
  - numpy
  - pandas
  - matplotlib
  - psutil
  # Jupyter archive
  # https://github.com/jupyterlab-contrib/jupyter-archive
  - jupyter-archive
  # Jupyter git
  # https://github.com/jupyterlab/jupyterlab-git
  - jupyterlab-git
  - pip:
    - bash_kernel
  # For the M2 course:
  - fastqc
  - fastp
  - bowtie
  - samtools
  - multiqc
  - qualimap
  - bedtools
  - htseq
  # R environment
  - r-irkernel
  - r-base>=4.1.0
  - r-tidyverse
  - r-rcpp
  - r-dt
  - r-repr
  - r-writexls
  - r-writexl
  - r-readxl
  - r-rcolorbrewer
  # to run r in python notebooks
  - rpy2
  - simplegeneric # for some reasons needed by rpy2
  # for the M2 course 
  - r-devtools
  - r-Matrix
  - r-lattice
  - r-fdrtool
  - r-rpart
  - r-RSQLite
  - r-gplots
  - r-locfit
